### ISSUE TITLE
GPU accelerated Whisper inference in Mediapipe?

### ISSUE THREAD

**Issue by sandorkonya** [googlesamples/mediapipe#114]
Hi there,
i really like the idea of low-code ML dev tools.
Especially the GPU acelerated inference on android devices!

@st-duymai & @PaulTR: 
1. is there a Whisper (audio-to-text) demo in scope? With streamlined/recorded audio real time into text transcription? I believe with the GPU support it could be done real time, given that there are [binaries that almost real time run on CPU](https://github.com/ggerganov/whisper.cpp).
2. if not, could one use .tflite models ([like this one](https://github.com/usefulsensors/openai-whisper)) to achieve the above with your framework?

thank you for your time and reply in advance!

**Comment by PaulTR** [comment]
So I haven't heard anything about audio-to-text yet, but I can definitely pass that feedback over to the MediaPipe Tasks engineering team.

As far as using a tflite model - MediaPipe Tasks is really designed for known tasks with some customizable features. If you want to use a different kind of TFLite model, I think the TensorFlow Lite interpreter API is going to be your best bet. The recommended way to use that is with the [Google play services TFLite implementation](https://www.tensorflow.org/lite/android/play_services).

Hopefully that at least gets you on the right track to move forward :) Thanks!

**Comment by sandorkonya** [comment]
@PaulTR thank you for your reply.
