### ISSUE TITLE
Lightweight hand tracking algorithm within min_hand_presence_confidence description

### ISSUE THREAD

**Issue by Chris0215** [googlesamples/mediapipe#117]
I saw a paragraph explaining "Otherwise, a lightweight hand tracking algorithm is used to determine the location of the hand(s) for subsequent landmark detection."
How does a lightweight hand tracking algorithm work?
Thanks.

**Comment by PaulTR** [comment]
So I asked our eng team about this and got an answer for you:

the hand landmarks detection model output a presence score.
If the presence score is high enough, we believe the hand is presence in the current frame. In the next frame, we use the detected hand landmarks to create a new bounding box  (by finding the bounding box enclosing all the landmarks, and slightly expanding it, so it has higher chance to enclose the tracked hand in the next frame).

If the presence score is low, we trigger the palm detection model again. 

The point here is, palm detection is time consuming, and we want to skip it as much as possible.
