### ISSUE TITLE
Low framerate in new segmentation solution

### ISSUE THREAD

**Issue by berkon** [googlesamples/mediapipe#121]
The new segmentation solution for the webcam has a much lower quality compared to the old legacy selfie - segmentation. At least the framerate is obviously much lower. The old solution worked very smoothly. Is there anything that can be tuned to get the same results?

**Comment by PaulTR** [comment]
Hey @berkon! I'm testing it today, but we have alpha9 now and _should_ have the fix for this. Thanks!

**Comment by berkon** [comment]
Thanks @PaulTR!

**Comment by PaulTR** [comment]
Alright updated from feature branch + reducing image size during processing to fix an OOM issue on the gallery mode.
