### ISSUE TITLE
How to run on darwin/iOS?

### ISSUE THREAD

**Issue by dennislysenko** [googlesamples/mediapipe#151]
Hey all 👋 

The previous version of Mediapipe had first class C++ support with the ability to run on iOS and documentation for this. 

Is this dropped from solutions like FaceMesh V2? I'm only seeing Android, Python and Web guides.

**Comment by PaulTR** [comment]
Hey @dennislysenko. Yeah we only have Android, Python, and web right now. iOS is planned and should be in preview soon.

**Comment by dennislysenko** [comment]
@PaulTR , that's great news, thanks for confirming! Just to clarify, does this FaceMesh V2 solution include an updated model that represents an improvement on the old one in terms of accuracy, or speed, or perhaps frame-by-frame performance for decoded videos? 

I'm not sure where to find docs that go into the differences in detail, other than that it seems to include blend shapes now.

**Comment by PaulTR** [comment]
So I do know there was a focus on performance when getting MP Tasks together. Here's the model card for [BlazeFace Short Range](https://storage.googleapis.com/mediapipe-assets/MediaPipe%20BlazeFace%20Model%20Card%20(Short%20Range).pdf). It looks like the [others need to be updated](https://developers.google.com/mediapipe/solutions/vision/face_detector#models), but I'll ask about that the next time I have my meeting with the docs team.

**Comment by PaulTR** [comment]
I'm going to close this one out for now. I have the action item to talk to docs about those last model cards and I'll send a message out to the announcement group once iOS is ready for testing. You can join that [here](https://groups.google.com/u/3/g/mediapipe-solutions-external-announce) :)
