### ISSUE TITLE
How to run two models at the same time on android?

### ISSUE THREAD

**Issue by NastyDemigod** [googlesamples/mediapipe#152]
Hello, I really need help
I need to collect the coordinates of the points of both hands and face from one frame. I have combined the code to search for [face points](https://github.com/googlesamples/mediapipe/tree/main/examples/face_landmarker/android) and [hand points](https://github.com/googlesamples/mediapipe/tree/main/examples/hand_landmarker/android). 
Now I have two FaceLandmarkerHelper and HandLandmarkerHelper files in my project. Nothing has changed in them, except the name of the inherited LandmarkerListener functions: onError, onResults, onEmpty. Now it's onErrorFace/onErrorHand, onResultsFace/onResultsHand, onEmptyFace/onEmptHand. 
In the CameraFragment, I similarly divided the variables into hands and face: imageAnalyzer, backgroundExecutor. And added a variable handLandmarkerHelper, faceLandmarkerHelper. The class itself inherits from HandLandmarkerHelper.LandmarkerListener и FaceLandmarkerHelper.LandmarkerListener.
All separated variables have duplicated code.

**Declaring variables:**
   
    private lateinit var handLandmarkerHelper: HandLandmarkerHelper
    private lateinit var faceLandmarkerHelper: FaceLandmarkerHelper

    private val viewModel: MainViewModel by activityViewModels()
    private var preview: Preview? = null 

    private var handIimageAnalyzer: ImageAnalysis? = null
    private var faceImageAnalyzer: ImageAnalysis? = null

    private var camera: Camera? = null 
    private var cameraProvider: ProcessCameraProvider? = null 
    private var cameraFacing = CameraSelector.LENS_FACING_FRONT

    private lateinit var handBackgroundExecutor: ExecutorService
    private lateinit var faceBackgroundExecutor: ExecutorService 

**In the function onViewCreated:**

        super.onViewCreated(view, savedInstanceState)

        // Initialize our background executor
        backgroundExecutor = Executors.newSingleThreadExecutor()
        faceBackgroundExecutor = Executors.newSingleThreadExecutor()

        // Wait for the views to be properly laid out
        fragmentCameraBinding.viewFinder.post {
            // Set up the camera and its use cases
            setUpCamera() // метод setUpCamera текущего класса
        }

        // Create the HandLandmarkerHelper that will handle the inference
        handBackgroundExecutor.execute {
            handLandmarkerHelper = HandLandmarkerHelper(
                context = requireContext(),
                runningMode = RunningMode.LIVE_STREAM,
                minHandDetectionConfidence = viewModel.currentMinHandDetectionConfidence,
                minHandTrackingConfidence = viewModel.currentMinHandTrackingConfidence,
                minHandPresenceConfidence = viewModel.currentMinHandPresenceConfidence,
                maxNumHands = viewModel.currentMaxHands,
                currentDelegate = viewModel.currentDelegate,
                handLandmarkerHelperListener = this
            )
        }
        faceBackgroundExecutor.execute {
            faceLandmarkerHelper = FaceLandmarkerHelper(
                context = requireContext(),
                runningMode = RunningMode.LIVE_STREAM,
                minFaceDetectionConfidence = viewModel.currentMinFaceDetectionConfidence,
                minFaceTrackingConfidence = viewModel.currentMinFaceTrackingConfidence,
                minFacePresenceConfidence = viewModel.currentMinFacePresenceConfidence,
                maxNumFaces = viewModel.currentMaxFaces,
                currentDelegate = viewModel.currentDelegate,
                faceLandmarkerHelperListener = this
            )
        }

**Part of the function bindCameraUseCases:**

        // ImageAnalysis. Using RGBA 8888 to match how our models work
        handImageAnalyzer =
            ImageAnalysis.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3)
                .setTargetRotation(fragmentCameraBinding.viewFinder.display.rotation)
                .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888)
                .build()
                // The analyzer can then be assigned to the instance
                .also {
                    it.setAnalyzer(handBackgroundExecutor) { image ->
                        detectHand(image) 
                    }
                }

        faceImageAnalyzer =
            ImageAnalysis.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3)
                .setTargetRotation(fragmentCameraBinding.viewFinder.display.rotation)
                .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888)
                .build()
                // The analyzer can then be assigned to the instance
                .also {
                    it.setAnalyzer(faceBackgroundExecutor) { image ->
                        detectFace(image)
                    }
                }

        // Must unbind the use-cases before rebinding them
        cameraProvider.unbindAll()

Is it possible to pass two analyzers to bindToLifcycle?  Continuation of the function bindCameraUseCases:

        try {
            // A variable number of use-cases can be passed here -
            // camera provides access to CameraControl & CameraInfo
            camera = cameraProvider.bindToLifecycle(
                this, cameraSelector, preview, handImageAnalyzer (or faceImageAnalyzer)
            )

            // Attach the viewfinder's surface provider to preview use case
            preview?.setSurfaceProvider(fragmentCameraBinding.viewFinder.surfaceProvider)
        } catch (exc: Exception) {
            Log.e(TAG, "Use case binding failed", exc)
        }

Or maybe somehow combine both analyzers in one? 
`imageAnalyzer = handImageAnalyzer + faceImageAnalyzer`

If you create one imageAnalyzer and one backgroundExecutor, then in this code:

        imageAnalyzer =
            ImageAnalysis.Builder().setTargetAspectRatio(AspectRatio.RATIO_4_3)
                .setTargetRotation(fragmentCameraBinding.viewFinder.display.rotation)
                .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888)
                .build()
                // The analyzer can then be assigned to the instance
                .also {
                    it.setAnalyzer(backgroundExecutor) { image ->
                        detectFace(image)
                    }
                    it.setAnalyzer(backgroundExecutor) { image ->
                        detectHand(image)
                    }
                }

the latter method will prevail (now detectHand)

**Comment by PaulTR** [comment]
So I haven't tried this, but I'm curious if you can pass the original image into the results method for face detection, then rather than doing the callback immediately, call hand detection on that image to combine the information into one overall object before returning.

That said, that's a gigantic pain and terrible user experience. I just messaged our relevant eng team to find out if we're working on a combined holistic API like we did with the [legacy MP solution](https://github.com/google/mediapipe/blob/master/docs/solutions/holistic.md). I think there's a solid value there and hopefully I have an answer soon.

**Comment by PaulTR** [comment]
Alright got confirmation - holistic is on a todo list for converting to the current MediaPipe Solutions framework, but I can't really give a timeline unfortunately. I'm really hoping the chaining through results idea works, otherwise this will be easier to do later in the developer preview stage. Sorry about that!
