### ISSUE TITLE
Dense face landmark definition

### ISSUE THREAD

**Issue by minhpvo** [googlesamples/mediapipe#155]
Hello, is there a definition of the location of each landmark in the dense model? If so, how is it corresponding to the vertices of FLAME, GHUM,  orPhoMoH models?

Thanks!

**Comment by PaulTR** [comment]
I'm going to hunt down whether or not we'll have an image that's useful for you. Right now we have a class called [FaceLandmarksConnections](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/java/com/google/mediapipe/tasks/vision/facelandmarker/FaceLandmarksConnections.java) that separates various points into their relevant parts of the face (lips, left eye, right eye, etc.) that might be useful.

As far as the other models, I have no idea :) I'm not familiar with them.

**Comment by PaulTR** [comment]
So our points don't exactly correspond to the other models. We're working on posting some documentation about points by index on an image, so I'll follow up here once I have it. Thanks!

**Comment by aiphuongle** [comment]
Yes, the doc would very help.

**Comment by PaulTR** [comment]
Alright we officially have a numbered [graphic up in the docs](https://developers.google.com/mediapipe/solutions/vision/face_landmarker) :) Going to close this out.

**Comment by jiamingkong** [comment]
Hi, I founded the numbered graphics, but the image is very hard to read since the font size of point indices was too small. Could I find this information elsewhere?
