### ISSUE TITLE
FLAME indices correspondence

### ISSUE THREAD

**Issue by AAAnani** [googlesamples/mediapipe#157]
Hello. 

I am using your FaceLandmarker found here: https://github.com/googlesamples/mediapipe/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb

Currently I am trying to use the dense landmarks while training a FLAME-based 3D model. Is there such a correspondence between the dense landmarks you produce (478 points) and the FLAME vertices? This repo (https://github.com/Zielon/metrical-tracker/tree/master/flame/mediapipe) seems to have found a correspondence for 105 points, but not the entire 478 points.

**Comment by PaulTR** [comment]
So it sounds like the FLAME vertices aren't matched up to what we produce. We just made a visualization of the points by their index number, so will have that in the documentation soon. I'll post an update here when we have it.

**Comment by AlaaAnani** [comment]
I see. Thanks a lot for your prompt response!
