### ISSUE TITLE
image segmentation on ipad safari

### ISSUE THREAD

**Issue by scdozer** [googlesamples/mediapipe#159]
Trying to troubleshoot why only on my ipad safari i get a full white mask back every time. The segmentation works fine on desktop but im not entirely sure how else to test/debug this. i do get a base64 image from the segmenter, but its always just a white image on ipad safari. 

just updated my computer and ipad to the lastest ios/safari 

> useEffect(() => {
>     const loadModel = async () => {
>       const audio = await FilesetResolver.forVisionTasks(
>         "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0/wasm"
>       );
>       const options = {
>         baseOptions: {
>           modelAssetPath: "/models/selfie_multiclass.tflite",
>           delegate: "GPU",
>         },
>         runningMode: "IMAGE",
>         outputCategoryMask: true,
>         outputConfidenceMasks: false,
>         displayNamesLocale: "en",
>       };
>       const segmenter = await ImageSegmenter.createFromOptions(audio, options);
>       setImageSegmenter(segmenter);
>     };
> 
>     loadModel();
>   }, []);
> 
>   const initializeCamera = async () => {
>     try {
>       const constraints = {
>         audio: false,
>         video: { facingMode: "user", width: 512, height: 768 },
>       };
>       const stream = await navigator.mediaDevices.getUserMedia(constraints);
>       const videoElement = videoRef.current;
>       videoElement.srcObject = stream;
>       videoElement.onloadedmetadata = () => {
>         videoElement.play();
>         setIsCameraInitialized(true);
>       };
>     } catch (error) {
>       console.error("Error accessing webcam:", error);
>       console.error(error.message);
>     }
>   };
> 
>   const takeSelfie = async () => {
>     const videoElement = videoRef.current;
>     const canvasElement = canvasRef.current;
>     const canvasCtx = canvasElement.getContext("2d");
> 
>     const { videoWidth, videoHeight } = videoElement;
>     canvasElement.width = 512;
>     canvasElement.height = 768;
> 
>     canvasCtx.drawImage(videoElement, 0, 0, 512, 768);
> 
>     const imageData = canvasCtx.getImageData(0, 0, 512, 768);
>     const imageUrl = canvasElement.toDataURL();
>     setImageURL(imageUrl);
>     await imageSegmenter.segment(imageData, callback);
>   };
> 
>   const callback = (result) => {
>     const canvasElement = canvasRef.current;
>     const canvasCtx = canvasElement.getContext("2d");
> 
>     const { width, height } = canvasElement;
>     const categoryMask = result.categoryMask.getAsUint8Array();
> 
>     const imageData = canvasCtx.getImageData(0, 0, 512, 768);
>     const data = imageData.data;
>     const headColor = [0, 0, 0, 255]; // Black color for head and hair
>     const whiteColor = [255, 255, 255, 255]; // White color for other parts
> 
>     for (let i = 0; i < categoryMask.length; i++) {
>       const categoryIndex = categoryMask[i];
> 
>       if (
>         categoryIndex == 1 ||
>         categoryIndex === 2 ||
>         categoryIndex == 3 ||
>         categoryIndex == 5
>       ) {
>         // Head and hair category indices
>         data[i * 4] = headColor[0];
>         data[i * 4 + 1] = headColor[1];
>         data[i * 4 + 2] = headColor[2];
>         data[i * 4 + 3] = headColor[3];
>       } else {
>         data[i * 4] = whiteColor[0];
>         data[i * 4 + 1] = whiteColor[1];
>         data[i * 4 + 2] = whiteColor[2];
>         data[i * 4 + 3] = whiteColor[3];
>       }
>     }
> 
>     canvasCtx.putImageData(imageData, 0, 0);
> 
>     const segmentedImageURL = canvasElement.toDataURL();
>     setSegmentedImageURL(segmentedImageURL);
>   };

**Comment by scdozer** [comment]
amazing @tyrmullen that did the trick!!!

**Comment by lebaudantoine** [comment]
I might have found a resolution to this issue. Please have a look https://github.com/google-ai-edge/mediapipe/issues/5879
