### ISSUE TITLE
[Android] Why doesn't the segmentation mask image match layout in pose detection result?

### ISSUE THREAD

**Issue by ows3090** [googlesamples/mediapipe#163]
Hello, I'm wonseok.
I got segmentation MPImage when i executed pose detection.
So i resized to fit origin image and show on it.
But It doesn't match location between pose detection and segmentation image.
It looks like biased left or right little. Why?

[origin image]
<img width="1348" alt="image" src="https://github.com/googlesamples/mediapipe/assets/34837583/f0d1da98-98fd-434f-b344-d22fee2eafb7">

[segmentation mask]
![image](https://github.com/googlesamples/mediapipe/assets/34837583/614b04da-652a-49e0-a436-1b03fbad0ded)

**Comment by PaulTR** [comment]
How does this look in portrait mode?

My guess is that it has to do with scaling in the helper, then scaling back in the overlay fragment.

**Comment by ows3090** [comment]
<img src="https://github.com/googlesamples/mediapipe/assets/34837583/6bdd0462-9e75-43d0-85ca-b4cdc767c157" width=300 height=650/>

I always shoot with the person in the center.
And the preview is set to 4:3 ratio, and the overlayView is constrained to the preview.

I show my code that drawing segmentation mask.
```kotlin
            try {
                if (poseLandmarkerResult.segmentationMasks().get().isNotEmpty()) {
                    val segmentation = poseLandmarkerResult.segmentationMasks().get().first()
                    val byteBuffer = ByteBufferExtractor.extract(segmentation)
                    val compressRatio = sqrt(byteBuffer.capacity().toFloat() / (segmentation.width * segmentation.height)).toInt()
                    val pixels = IntArray(byteBuffer.capacity())
                    for (i in pixels.indices) {
                        // Using unsigned int here because selfie segmentation returns 0 or 255U (-1 signed)
                        // with 0 being the found person, 255U for no label.
                        // Deeplab uses 0 for background and other labels are 1-19,
                        // so only providing 20 colors from ImageSegmenterHelper -> labelColors
                        val index = byteBuffer.get(i).toInt()
                        val color = if (index == 0) Color.parseColor("#FF0000") else Color.TRANSPARENT
                        pixels[i] = color
                    }
                    
                    val image = Bitmap.createBitmap(
                        pixels,
                        segmentation.width * compressRatio,
                        segmentation.height * compressRatio,
                        Bitmap.Config.ARGB_8888
                    )

                    val bitmap = Bitmap.createScaledBitmap(
                        image,
                        width,
                        height,
                        false
                    )
                    canvas.drawBitmap(bitmap, 0f, 0f, null)
                }
```

**Comment by PaulTR** [comment]
Out of curiosity, have you had a chance to look over the segmentation example? I won't be able to get to trying this any time soon myself, unfortunately, but I'm betting you might have some luck using the [logic here](https://github.com/googlesamples/mediapipe/blob/main/examples/image_segmentation/android/category_mask/app/src/main/java/com/google/mediapipe/examples/imagesegmenter/OverlayView.kt) mixed with the pose landmarker.

Let me know if you make some progress on it as I think it'd be something really useful for the community, too :)

**Comment by PaulTR** [comment]
Closing due to 2 weeks of inactivity
