### ISSUE TITLE
How to use the NPU built into the device

### ISSUE THREAD

**Issue by ows3090** [googlesamples/mediapipe#167]
Does mediapipe only support CPU and GPU?
If the mediapipe support NPU , May you let me know how to use it?

**Comment by PaulTR** [comment]
Yeah at this point it's just CPU and GPU.

**Comment by ows3090** [comment]
Thank you for replying
Therefore Does the mediapipe plan to support NPU?

**Comment by PaulTR** [comment]
So unfortunately I can't really say anything about future plans one way or the other, but I can definitely write this down as a feature request so we can at least track what our devs are interested in. Sorry about that!

**Comment by PaulTR** [comment]
Added here for public tracking https://github.com/googlesamples/mediapipe/discussions/168

**Comment by ows3090** [comment]
I always get help from you.
Thank you.

**Comment by ows3090** [comment]
Hello
I'm sorry I'am wondering one more thing.
Can't I use NNAPI in mediapipe?
If I can use it, Can you let me know how to use NNAPI?

**Comment by PaulTR** [comment]
Unfortunately the NNAPI delegate isn't supported right now. I'd say that lumps into the same feature request :)
