### ISSUE TITLE
what is the diffenent between z in pose_landmarks and z in pose_world_landmarks?

### ISSUE THREAD

**Issue by ghoshaw** [googlesamples/mediapipe#173]
Hi, following the guide, I can run pose estimate of human, but the pose_landmarker_result confused me.  There both have z in pose_landmarks and  pose_world_landmarks, they are all relative depth, but they are different in value, so what are their definiation?

**Comment by PaulTR** [comment]
Hey sorry just saw this. Pose landmark Z is in relative scale to the X axis in a picture (so 0.0 -> 1.0), and world landmarks Z tries to make a guess at that distance in terms of meters. Hope that helps!
