### ISSUE TITLE
Custom Trained Model

### ISSUE THREAD

**Issue by ProfessorHT** [googlesamples/mediapipe#183]
Hello,

I am trying to implement the android application for the image segmentation task. (https://github.com/googlesamples/mediapipe/tree/main/examples/image_segmentation/android)

I have an h5 model trained on my own data. 

1. Can you please post a method to transform an h5 to tflite? 
2. Can you please specify also where can i change the image size to be compatible with my model?

**Comment by PaulTR** [comment]
1. So I haven't done this myself, but the first result for the search 'h5 to tflite' brings up this StackOverflow post: https://stackoverflow.com/questions/53256877/how-to-convert-kerash5-file-to-a-tflite-file

2. [This is where the resizing happens](https://github.com/googlesamples/mediapipe/blob/main/examples/image_segmentation/android/confidence_mask/app/src/main/java/com/google/mediapipe/examples/imagesegmenter/ImageSegmenterHelper.kt#L155a).

**Comment by ProfessorHT** [comment]
Thank you
