### ISSUE TITLE
Permissions for  READ_EXTERNAL_STORAGE or READ_MEDIA_IMAGES

### ISSUE THREAD

**Issue by Deveshbhatla** [googlesamples/mediapipe#184]
Why does the application sample doesn't include the permissions to READ_EXTERNAL_STORAGE?

https://github.com/googlesamples/mediapipe/blob/main/examples/image_classification/android/app/src/main/java/com/google/mediapipe/examples/imageclassification/fragments/PermissionsFragment.kt

The application has a gallery fragment that accesses the images stored on the device, but the application doesn't ask for media permissions either via READ_EXTERNAL_STORAGE or READ_MEDIA_IMAGES(compileSdk 33 or Android 13). Nor the permissions are included in the Manifest File: https://github.com/googlesamples/mediapipe/blob/main/examples/image_classification/android/app/src/main/AndroidManifest.xml

Can someone please explain why the READ permission is not required?

**Comment by st-duymai** [comment]
Hi @Deveshbhatla 
In our app, we use the registerForActivityResult() API with ActivityResultContracts to get content such as images and videos.[Read more here](https://developer.android.com/training/basics/intents/result).
This way, we don't have to directly access the device storage, and we don't need to ask the user for permission to access their files. The app that returns the Uri for our apps is the app that needs the permission.
