### ISSUE TITLE
Custom Trained Model

### ISSUE THREAD

**Issue by ProfessorHT** [googlesamples/mediapipe#185]
Hello,

Following my old issue  #183. Thank you for the first reponse but concerning the second question i have a model with an input of "1 x 1024 x 1024 x 1" and when i apply change in the same place you have mentioned i got the following error:
"java.lang.IllegalArgumentException: Error occurred when initializing ImageSegmenter: The input tensor should have dimensions 1 x height x width x 3. Got 1 x 1024 x 1024 x 1." Do you have any solution to this?

Thank you

**Comment by PaulTR** [comment]
Can you share more detail please?

Platform
MVP sample to narrow down issue (if it's a more complex case)
Copy of model
Info on how you made the model
Have you tested the model on multiple platforms (to narrow down if it's Android/web/python specific) or other tools (tflite)?

Thanks

**Comment by PaulTR** [comment]
Closing out due to inactivity.
