### ISSUE TITLE
A bug of Image generation task guide

### ISSUE THREAD

**Issue by StudyingLover** [googlesamples/mediapipe#216]
In this session[Install and run the Image Generator demo app](https://developers.google.com/mediapipe/solutions/vision/image_generator#install_and_run_the_image_generator_demo_app), `adb push <output_path>/. /data/local/tmp/image_generator/bins` is not right besacuse I got this mistake 

```
push: output/./cond_stage_model.transformer.text_model.final_layer_norm.bias.bin -> /data/local/tmp/image_generator/bins/cond_stage_model.transformer.text_model.final_layer_norm.bias.bin
failed to copy 'output/./cond_stage_model.transformer.text_model.final_layer_norm.bias.bin' to '/data/local/tmp/image_generator/bins/cond_stage_model.transformer.text_model.final_layer_norm.bias.bin': secure_mkdirs failed: Operation not permitted
```
I think the correct command should be `adb push <output_path>/ /data/local/tmp/image_generator/bins`.

I didn't find where is the source file to PR,so I ask this issue.

**Comment by PaulTR** [comment]
Closing this out since the conversation is happening in a separate issue.

**Comment by StudyingLover** [comment]
@PaulTR Sorry , I don't think it is a same issue althought it is be mentioned in another issue .
This issue is about a mistake about your guide , not about app crashed when init or generatation.
