### ISSUE TITLE
Use face mesh to transform face

### ISSUE THREAD

**Issue by arianaa30** [googlesamples/mediapipe#223]
Using the Face landmark detection we can "get" 3D face landmarks and a mesh. But how would it be possible to use it to "transform" and change facial landmarks? Say can we use that to make the eye bigger or the lips smaller? Any tips or examples would be appreciated.

**Comment by PaulTR** [comment]
That's a much bigger conversation and scope than this repo (and my bandwidth :p) is prepared for. Basically you'd need a graphic and some OpenGL goodness to start applying 3D graphics in your app. Now if anyone wanted to make that as an example and either submit it as a PR or write a tutorial, I'd be a huge fan.

**Comment by arianaa30** [comment]
OK. So with MediaPipe we can only "get" the mesh and landmakrs, but not "set" it back after changing, right? At least it's not straightforward?

**Comment by PaulTR** [comment]
I don't get what you mean by 'set', but yeah MediaPipe basically looks at an image/frame and returns the results for those landmarks to you. What you do with that info is where devs get to be creative with whatever problems they're trying to solve.
