### ISSUE TITLE
About getting both Android FaceDetector and FaceLandmarker at the same time

### ISSUE THREAD

**Issue by RavenGluttonous** [googlesamples/mediapipe#240]
My requirement is to process video frames in RunningMode, first use Android FaceDetector to get the face position, crop the image, and then use FaceLandmarker to get the feature points, but to get the result of faceDetector, it takes 50~70 milliseconds to test mediapipe to process a frame, while to get the result of faceLandmarker, it takes 90~150 milliseconds to test mediapipe to process a burst. However, to get the result of FaceDetector, it takes 50~70 ms to process one frame in mediapipe, and to get the result of FaceLandmarker, it takes 90~150 ms to process one frame in mediapipe, which takes too long, how can I get the position of the face and the feature points at the same time in a single call to the api?

**Comment by PaulTR** [comment]
So right now you can't because they're built as separate tasks, but I'll put in a feature request for you :)
