### ISSUE TITLE
Request Face Stylizer pre-build apk

### ISSUE THREAD

**Issue by BakaLee** [googlesamples/mediapipe#243]
Can someone please share a pre-build Face Stylizer android apk link.

**Comment by PaulTR** [comment]
Hey BakaLee. That kind of falls outside the scope of this repo, but is there a particular step blocking you from building this with a dev environment? Maybe there's something I can help walk you through.

**Comment by BakaLee** [comment]
I wanted to try it out on my android device. But since I don't have a PC nor do I know how to code. It will be awesome if anyone could share their pre-build demo apk.

**Comment by PaulTR** [comment]
Oh I see. So rather than using an APK that someone builds (probably not the case, but because this is an official repo I need to lean more on the cautious side) that could contain more than just the sample code, I'd actually recommend checking out our web version of the tool. It uses the same models and underlying task code :) I think this should be exactly what you're looking for to get an idea for how it all works.

https://mediapipe-studio.webapps.google.com/studio/demo/face_stylizer

**Comment by BakaLee** [comment]
> Oh I see. So rather than using an APK that someone builds (probably not the case, but because this is an official repo I need to lean more on the cautious side) that could contain more than just the sample code, I'd actually recommend checking out our web version of the tool. It uses the same models and underlying task code :) I think this should be exactly what you're looking for to get an idea for how it all works.
> 
> https://mediapipe-studio.webapps.google.com/studio/demo/face_stylizer

Thank you for the response.
I have already tried out the web version and it really amazing. The reason why I am requesting of a pre-build demo apk is because I wanted to try it out on device offline.
It would be really helpful if you could share a pre-build demo apk.

**Comment by PaulTR** [comment]
So with the Studio version, it is actually happening all on-device :) MediaPipe is written at the C++ layer, and then Android/web/iOS/RaspberryPi/etc all wrap that, so it really is the same functionality that you'd see. Unfortunately though I won't be able to provide the APK in this case though without it going through the play store and a whole bunch of other processes - I did check, it's just not something we can really do right now :(.

**Comment by BakaLee** [comment]
> So with the Studio version, it is actually happening all on-device :) MediaPipe is written at the C++ layer, and then Android/web/iOS/RaspberryPi/etc all wrap that, so it really is the same functionality that you'd see. Unfortunately though I won't be able to provide the APK in this case though without it going through the play store and a whole bunch of other processes - I did check, it's just not something we can really do right now :(.

No problem, thank you so much.
