### ISSUE TITLE
Module 'mediapipe.tasks.python.vision' has no attribute 'FaceLandmarkerOptions'

### ISSUE THREAD

**Issue by szreik** [googlesamples/mediapipe#246]
Hello! I am trying to run this face landmarker code locally (not on Google Colab/Jupyter notebook) and I am getting an error during this code segment: 
`options = vision.FaceLandmarkerOptions(base_options=base_options,
                                          output_face_blendshapes=True,
                                         output_facial_transformation_matrixes=True,
                                          num_faces=1)`

The error is `Module 'mediapipe.tasks.python.vision' has no attribute 'FaceLandmarkerOptions'`

Does `wget -O face_landmarker_v2_with_blendshapes.task -q https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task` not work when working on a local machine? I can't think of what else could be causing this. Any insight would be very appreciated!

**Comment by PaulTR** [comment]
Weird, no I just ran the wget command on my mac and it worked. What kind of computer are you using?

**Comment by szreik** [comment]
Also a mac. Just realized I can only download mediapipe 0.9.1.0 (and I'm using python 3.9). Could this be the issue?

**Comment by PaulTR** [comment]
Oh yeah that can definitely be an issue. I'd ditch requesting any version numbers and just using the latest. I'll look over the sample we have on GitHub to update that, too.

**Comment by szreik** [comment]
Solved! It was because I was not using Mediapipe 0.10.5, and I was not able to download that version using pythion 3.9. Updating to python 3.10 allowed me to download the latest version of mediapipe.
