### ISSUE TITLE
Is there a a version of the cannonical face 3Dmodel (or any other 3Dmodel) That has the 52 blendshapes of facemeshv2

### ISSUE THREAD

**Issue by Hakazaba** [googlesamples/mediapipe#256]
Hi, i'm currently looking for an example face mesh that has the blendshapes which new blendshape face mesh feature is build for. Does anyone know where i could find one?

**Comment by PaulTR** [comment]
Hey. I don't think we have anything that acts as an example for all 52 blendshapes, but I'll put in a request for something. You might have better luck just trying to make different expressions to see what does what until then :)
