### ISSUE TITLE
Incorrect code line in the documentation

### ISSUE THREAD

**Issue by xiaoxiong1006** [googlesamples/mediapipe#258]
I was going through the documentation on the [Google Codelabs page for MediaPipe Object Detection Web](https://codelabs.developers.google.com/mp-object-detection-web?hl=zh_cn#4) and noticed a small mistake in the code snippet under the section **Handling and displaying prediction results**.

The current code line reads:

``` javascript
for (const detection of detections) {
```
However, based on the context and proper usage, I believe it should be:

``` javascript
for (const detection of result.detections) {
```

I suggest updating the documentation to reflect the correct code. This will help other developers avoid any confusion.

**Comment by PaulTR** [comment]
Thanks for the update. Just went to check and it looks like it was fixed on our end, but it just needs to be updated (the original author is no longer with the team, so it fell through the cracks). I'll get that pushed. Thanks!
