### ISSUE TITLE
Face landmarks not available on Mac os Python

### ISSUE THREAD

**Issue by piekaa** [googlesamples/mediapipe#262]
Hey, is `FaceLandmarker` planned to be available in Python library on Mac os?

```
AttributeError: module 'mediapipe.tasks.python.vision' has no attribute 'FaceLandmarkerOptions'
```

I guess that's related to version, cos for linux 0.10.7 it works

```
pip install mediapipe==0.10.7
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.7 (from versions: 0.8.4.2, 0.8.5, 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8.1, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0)
ERROR: No matching distribution found for mediapipe==0.10.7
```

Thanks ;)

**Comment by PaulTR** [comment]
Weird. I'll check into it when I'm back at my computer. I ran the raspberry
pi python version on my mac yesterday, so can you give that a shot?

**Comment by piekaa** [comment]
Thanks for resposne  @PaulTR  
I can try that tomorrow, g2g now :/
