### ISSUE TITLE
How to train a object detector model on our custom data?

### ISSUE THREAD

**Issue by aishwarya123mathpati** [googlesamples/mediapipe#264]

**Comment by PaulTR** [comment]
So I have a video coming out on this soon, but I'm not entirely sure when it'll have finished the post-recording steps. What I did was label a lot of individual images with a tool called [Label Studio](https://labelstud.io/) - make sure you have your training data and about 10% more data in a separate annotations project for label studio - and then export both sets of data in the coco format to run it through this [codelab](https://developers.google.com/mediapipe/solutions/customization/object_detector)

This'll get you to a point where you should be able to have your own tflite model that works specifically for the data you train it for, like my example model here that detects and classifies different shaped/colored blocks

![ModelMaker-Video-Segment9](https://github.com/googlesamples/mediapipe/assets/2335087/207107f1-431e-4f7e-b4dc-2a28a71dce7d)
