### ISSUE TITLE
Run face_stylizer.ipynb error by Service "kGpuService"

### ISSUE THREAD

**Issue by h3clikejava** [googlesamples/mediapipe#289]
I never chang any code, just want to fine tune. Use default T4 GPU

![image](https://github.com/googlesamples/mediapipe/assets/4688773/8eab73c2-c07e-4e0e-9edb-4c4463bb177a)

Downloading https://storage.googleapis.com/mediapipe-assets/face_landmarker_v2.task to /tmp/model_maker/face_stylizer/face_landmarker_v2.task
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-5-b3643ca17ef4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 data = face_stylizer.Dataset.from_image(filename=style_image_path)

3 frames
[/usr/local/lib/python3.10/dist-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py](https://localhost:8080/#) in __init__(self, graph_config, running_mode, packet_callback)
     68           'callback should not be provided.'
     69       )
---> 70     self._runner = _TaskRunner.create(graph_config, packet_callback)
     71     self._running_mode = running_mode
     72 

RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_face_stylizer_facestylizergraph__mediapipe.tasks.TensorsToImageCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL

**Comment by kuaashish** [comment]
Hi @h3clikejava,

This issue has been fixed, Can you please try to reproduce the issue with runtime as GPU and let us know if you have still encountering the issue. 

Thank you

**Comment by PaulTR** [comment]
Closing since we haven't heard back.
