### ISSUE TITLE
I want to know id of key points at mouth area.

### ISSUE THREAD

**Issue by y200504040u** [googlesamples/mediapipe#306]
I searched the documents.
[https://developers.google.com/mediapipe/solutions/vision/face_landmarker#configurations_options](url)
But the joints at the corners of the mouth shown in the full size image are too dense.
Please provide some guidance.
Thanks a lot.

**Comment by y200504040u** [comment]
I just drew them.
Self-ask and self-answer.
Friends in need, help yourselves.
![mouth1](https://github.com/googlesamples/mediapipe/assets/57352939/ed04152f-761d-4284-bcb6-22bf4de502da)

**Comment by PaulTR** [comment]
Thanks for the feedback! I'm going to pass it along to see what we can do and close this out.
