### ISSUE TITLE
What information does the Z of the key point of the hand represent?

### ISSUE THREAD

**Issue by lucker26** [googlesamples/mediapipe#311]
The output coordinates of hand key points are x,y,z y and z, where x and y can be multiplied by the width and height of the image to get the position of the key point in the image, so how does z define the depth information of the key point? Is it the distance between the key point and the camera or the distance between the key point and the wrist?

**Comment by PaulTR** [comment]
Distance from the camera with a key point on the wrist acting as 0. Global tries to approximate in meters, other scales to roughly the same level as x.

**Comment by lucker26** [comment]
Ok, thank you for your answer.
