### ISSUE TITLE
Unresolved reference: LlmInference

### ISSUE THREAD

**Issue by dengzheng-cloud** [googlesamples/mediapipe#352]
to make some modification in mediapipe cc code
i replace implementation ("com.google.mediapipe:tasks-genai:0.10.11") in build.gradle.kts with implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar, *.aar"))))
in app/libs folder i compiled an **tasks_genai.aar** lib, whic is compiled as followed:

1. git clone https://github.com/google/mediapipe.git && cd mediapipe
2. bash ./setup_android_sdk_and_ndk.sh
3. bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --config=android_arm64 --features=-legacy_whole_archive --copt=-fvisibility=hidden --copt=-ffunction-sections --copt=-fdata-sections --copt=-fstack-protector --copt=-Oz --copt=-fomit-frame-pointer --linkopt=-Wl,--gc-sections,--strip-all mediapipe/tasks/java/com/google/mediapipe/tasks/genai:tasks_genai

with this aar and build this project i got error Unresolved reference: LlmInference, after unzip aar file , could find the llminference.class and libllm_inference_engine_jni.so, could any body give an advice, thx

**Comment by didwldn3032** [comment]
Did you run it as an emulator

**Comment by dengzheng-cloud** [comment]
> Unresolved reference: LlmInference, after unzip aar file , could find the llminference.class and libllm_

just give up that quickly and switch to another project. will close this issue. hope google will release how to quantize model.
