### ISSUE TITLE
gesnture recognizer can not run on windows

### ISSUE THREAD

**Issue by jinfagang** [googlesamples/mediapipe#53]
gesnture recognizer can not run on windows

**Comment by PaulTR** [comment]
Hi @jinfagang! Could you please provide more details?

Are you using the Python example or web?
What OS version?
Browser version (if applicable)
Error messages you receive?

Anything else that could be helpful in replicating the issue is also important.

Thanks!

**Comment by PaulTR** [comment]
Another thing that may be worth trying is updating the mediapipe dependency to 0.9.1 since it sounds like Windows support was updated in that version.

**Comment by PaulTR** [comment]
Sounds like we have some updates coming along now and I haven't heard back in a week, so closing thing out.

Thanks for the report! :)
