### ISSUE TITLE
Is there any difference between this framework and the [https://github.com/google/mediapipe] on android platform?

### ISSUE THREAD

**Issue by heimashi** [googlesamples/mediapipe#63]
Is there any difference between this framework and the [https://github.com/google/mediapipe](https://google.github.io/mediapipe/getting_started/android.html) on android platform？ Or are they compatible? 

I found the maven depends on are different:
[com.google.mediapipe:solution-core:latest.release](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facedetection/build.gradle#L39)
`implementation 'com.google.mediapipe:solution-core:latest.release'`

[com.google.mediapipe:tasks-vision:0.1.0-alpha-5](https://github.com/googlesamples/mediapipe/blob/main/examples/gesture_recognizer/android/app/build.gradle#L101)
`implementation 'com.google.mediapipe:tasks-vision:0.1.0-alpha-5'`

Can they migrate to each other? Or is the model file `xx.tflite` they use compatible?

**Comment by PaulTR** [comment]
Hi @heimashi!

This iteration of MediaPipe Tasks is designed specifically for more out-of-the-box solutions (this, combined with MediaPipe Model Maker and MediaPipe Studio are all parts of a product called MediaPipe Solutions).  I'd think of it more as the next iteration on MediaPipe. This does run the old MediaPipe framework under the hood, but the Java (Android) layers are different and incompatible.

As we continue to develop this framework out, it will include all of the current MediaPipe solutions, so migration should be possible as far as feature set. The model files, however, will not be compatible as MediaPipe Tasks requires additional metadata that was not necessary for the models under the older solution.

Thanks!

**Comment by heimashi** [comment]
Hi @PaulTR  
Thanks for your reply!
Will the new mediapipe be open source? I only found sample but not source code.

**Comment by PaulTR** [comment]
I'll double check, but I don't believe so. If I find anything different I'll let you know.
