### ISSUE TITLE
how to combine a custom model to default one?

### ISSUE THREAD

**Issue by fan123199** [googlesamples/mediapipe#74]
I have follow the page https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/customize and get a custom model `gesture_recognizer.task` that can recognize  rock paper scissors. 

And I found Android SDK can only load one model. So how can I use this model conbime with the default one https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer#models

**Comment by fan123199** [comment]
Thank you for you answer. Actualy the first answer is what I want. 

Because my real purpose is that my demo app can regconize  rock paper scissors , and also "👍, 👎, ✌️, ☝️, ✊, 👋, 🤟" at same time.

As you answer, I need to train all gesture from images. So  How could I  get the source dataset of default demo model here https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer#models ?  

I thought it would be offered by mediapipe official.  So that can let us easly use the hand guesture model.

**Comment by PaulTR** [comment]
So I haven't been able to get an exact answer on where our data for the model came from, but I'd really recommend checking out Kaggle for datasets that would be relevant. This [one in particular](https://www.kaggle.com/datasets/kapitanov/hagrid) looks like it might have the gestures you're wanting that can be mixed in with the rock paper scissors data.
