### ISSUE TITLE
AAR Unity porting error

### ISSUE THREAD

**Issue by Hoongcha** [googlesamples/mediapipe#84]
While converting the gesturerecognizer example into AAR and inserting it into Unity to call an activity and get a value, an error like this log and it says that initialization failed. 

```
native  com.DefaultCompany.SampleAPI  I  I20230329 11:05:49.779655 14280 resource_util_android.cc:77] Successfully loaded: gesture_recognizer.task

QCamera  and...e.camera.provider@2.4-service  I  <HAL><I> openCamera: 794: [KPI Perf]: X PROFILE_OPEN_CAMERA camera id 0, rc: 0

 LGCameraPerf-8996ac_OOS and...e.camera.provider@2.4-service  E  powerHintInternal_LGE: 353: mEnable = 0, enable = 1 PowerHint::CAMERA_STREAMING = 12

LGCameraPerf-8996ac_OOS and...e.camera.provider@2.4-service  E  powerHintInternal_LGE: 376: powerHint = 11, enable = 1,

QCamera  and...e.camera.provider@2.4-service  I  <HAL><I> initialize: 1097: E :mCameraId = 0 mState = 1

 sensors_ha...otionAccel and....hardware.sensors@1.0-service  D  processInd: LP2: X: 0.296753 Y: 1.117096 Z: 9.717972 SAM TS: 2602640251 HAL TS:79423187446215 elapsedRealtimeNano:79423270247980

sensors_hal_Ctx         and....hardware.sensors@1.0-service  D  poll:polldata:1, sensor:54, type:499898101, x:0.296753 y:1.117096 z:9.717972

sensors_hal_Util        and....hardware.sensors@1.0-service  D  waitForResponse: timeout=0

BluetoothRemoteDevices  com.android.bluetooth    D  Property type: 1

 6519-6749  BluetoothRemoteDevices  com.android.bluetooth   W  Skip name update for C0:F0:FB:27:E3:C2

 QCOM PowerHAL  android.hardware.power@1.2-service   I  Preview power hint start

BluetoothRemoteDevices  com.android.bluetooth  D  Property type: 4

 BluetoothRemoteDevices  com.android.bluetooth    W  Skip class update for C0:F0:FB:27:E3:C2

native                  com.DefaultCompany.SampleAPI         I  I20230329 11:05:49.785691 14280 hand_gesture_recognizer_graph.cc:250] Custom gesture classifier is not defined.

QCamera   and...e.camera.provider@2.4-service  I  <HAL><I> initialize: 1130: X

 tflite   com.DefaultCompany.SampleAPI         E  The supplied buffer is not 4-bytes aligned

tflite    com.DefaultCompany.SampleAPI         E  The model allocation is null/empty

 native     com.DefaultCompany.SampleAPI         E  E20230329 11:05:49.786113 14280 graph.cc:472] Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty

GestureRec...r 41116847 com.DefaultCompany.SampleAPI         E  MP Task Vision failed to load the task with error: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty

```

Why does this log :( I don't know because I don't have knowledge about TensorFlow.
+) I confirmed that it works well when inserting AAR through Android Studio.

**Comment by PaulTR** [comment]
Without more info on how you're building your app, I can't give you an exact answer. That said, MediaPipe Task has not currently been tested for Unity (there's a _lot_ of differences in Unity bridging vs working in pure Android). Your best bet would be creating a detailed writeup of what you're doing to share as a feature request at https://github.com/google/mediapipe :)

**Comment by Hoongcha** [comment]
> Without more info on how you're building your app, I can't give you an exact answer. That said, MediaPipe Task has not currently been tested for Unity (there's a _lot_ of differences in Unity bridging vs working in pure Android). Your best bet would be creating a detailed writeup of what you're doing to share as a feature request at https://github.com/google/mediapipe :)

Thank you for the reply. May I know why this error occurs? (last 4 line)

**Comment by PaulTR** [comment]
Like I said, I can't know without more detail on how you're using the package, but also MediaPipe Task has not been tested for Unity yet, so it could be any number of things across a large scope.

**Comment by Hoongcha** [comment]
> Like I said, I can't know without more detail on how you're using the package, but also MediaPipe Task has not been tested for Unity yet, so it could be any number of things across a large scope.

ah... ok Thx have a nice day :)
