### ISSUE TITLE
How to run python example on GPU?

### ISSUE THREAD

**Issue by HWT-WalterHu** [googlesamples/mediapipe#86]
I followed the Python example in Colab notebook(installed mediapipe by pip), but found the GPU seemed like not being occupied.  Is there a specific mediapipe version or installation option to use GPU device?

**Comment by PaulTR** [comment]
So I just checked on this - currently there's no support for GPUs in most cases, though if you're using Linux then you can build the Python wheels from [source](https://github.com/google/mediapipe).
