### ISSUE TITLE
some problems with the rear camera

### ISSUE THREAD

**Issue by Lookforward666** [googlesamples/mediapipe#88]
When I switch phone camera to back, like this CameraSelector.LENS_FACING_BACK. When the phone camera recognizes the hand, the real-time refresh node and line segment will not accurately fall on the hand, but slightly offset. This will not happen after switching to the front camera. How to optimize and deal with this problem?

**Comment by PaulTR** [comment]
Hi @Lookforward666, which sample are you running? If it's face detection, then I'm betting it has to do with post scaling (The front and rear camera are mirrored).

Go into the helper file and remove postScale from like 261

                postScale(
                    -1f,
                    1f,
                    imageProxy.width.toFloat(),
                    imageProxy.height.toFloat()
                )

**Comment by Lookforward666** [comment]
Thanks，it has been solved. By the way,I`m running gesture recognizer demo.

**Comment by Lookforward666** [comment]
Thanks，it has been solved. By the way,I`m running gesture recognizer demo.

**Comment by PaulTR** [comment]
Cool glad you got that working.
