### ISSUE TITLE
All CodePen examples for `vision` are failing

### ISSUE THREAD

**Issue by Neilblaze** [googlesamples/mediapipe#94]
### Description 

The following CodePen demos (examples) are failing because of dependency incompatibility for MediaPipe **Tasks Vision** package:

1. [Background Segmenter (web)](https://github.com/googlesamples/mediapipe/blob/50b9778d2ecac317032996812508371f0f51b90d/tutorials/background_segmenter/code/index.js#L72)
2. [MediaPipe GestureRecognizer (web)](https://codepen.io/mediapipe-preview/pen/zYamdVd)
3. [MediaPipe HandLandmarker (web)](https://codepen.io/mediapipe-preview/pen/gOKBGPN)
4. [MediaPipe Image Classifier (web)](https://codepen.io/mediapipe-preview/pen/BaVZejK)
5. [MediaPipe Image Embedder (web)](https://codepen.io/mediapipe-preview/pen/yLqxbaZ)
6. [MediaPipe Image Segmentation (web)](https://codepen.io/mediapipe-preview/pen/xxJNjbN)
7. [MediaPipe Interactive Image Segmentation (web)](https://codepen.io/mediapipe-preview/pen/ZEqzpRg)
8. [MediaPipe Object Detection (web)](https://codepen.io/mediapipe-preview/pen/vYrWvNg)

> I initially assumed that it was an issue with CodePen, but I can confirm that it's valid since I've tested most of them locally too.

cc: @jenperson, @PaulTR 

### Screenshot 🖼️ 
The error log populates an issue with building the "@mediapipe/tasks-vision" package [`@mediapipe/tasks-vision@v0.1.0-alpha-10`]

![image](https://user-images.githubusercontent.com/48355572/231891658-335dd5f2-ac36-4329-a05d-fafa23775e4c.png)

### Solution ❔ 

💡 0.1.0-alpha-10 just got released just 6 hours ago, while 0.1.0-alpha-9 got released 2 days ago. Release versions can be explored over [here](https://www.npmjs.com/package/@mediapipe/tasks-vision?activeTab=versions).

The easy fix is to update the CDN → **`https://cdn.skypack.dev/@mediapipe/tasks-vision@latest`** with either `https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision` (*stable*) or better "[**https://cdn.skypack.dev/@mediapipe/tasks-vision@0.1.0-alpha-9**](https://cdn.skypack.dev/@mediapipe/tasks-vision@0.1.0-alpha-9)" (*latest stable*) & you're good to go! 🚀 

---

**P.S.**: Please consider adding an `Issue Template` as well as `Stale bot` for this repository or better import the same one from [here](https://github.com/google/mediapipe/tree/master/.github) & set the config value accordingly. If assigned, I'd love to raise a PR for the same! 😄 

<br/>

**OS** : <img src="https://user-images.githubusercontent.com/48355572/229278766-2fb7f4b8-4d1d-441c-a250-49b56aabb292.png" width="15px" height="15px"> Ubuntu (22.04 LTS, x64)  &nbsp; / &nbsp; <img src="https://user-images.githubusercontent.com/48355572/229278633-299ddd26-07ae-4862-9a90-357add334f19.png" width="15px" height="15px"> Windows 10 Pro (x64) 
**Browser** : 
- <img src="https://user-images.githubusercontent.com/48355572/229278869-fd29ec92-c61e-48a6-bdca-aa6d27ce7900.png" width="15px" height="15px"> Google Chrome — Version 111.0.5563.147 (Official Build) (64-bit)
- <img src="https://user-images.githubusercontent.com/48355572/231897450-5f35f8a9-2a05-44ba-963d-1eca9936df85.png" width="15px" height="15px"> Microsoft Edge [Version 112.0.1722.39 (Official build) (64-bit)]

**Comment by jenperson** [comment]
Thank you for bringing this to my attention! There has been a new package release that resolves the issue. Feel free to re-open if this problem persists for you.
